# Generated by Django 6.0.1 on 2026-03-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_area_m2_property_bathrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Emri i Plotë')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/photos/', verbose_name='Foto')),
                ('specialization', models.CharField(choices=[('residential', 'Rezidenciale'), ('commercial', 'Komerciale'), ('land', 'Toka'), ('rental', 'Qira'), ('luxury', 'Luksoze')], default='residential', max_length=50, verbose_name='Specializimi')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Vjet Eksperiencë')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Rating')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Prona të Shitura')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='I Zgjedhur (Featured)')),
                ('show_on_about', models.BooleanField(default=True, verbose_name='Shfaq në About')),
                ('role', models.CharField(default='Agjent Imobiliar', max_length=100, verbose_name='Titulli/Roli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agjent',
                'verbose_name_plural': 'Agjentë',
                'ordering': ['-is_featured', 'full_name'],
            },
        ),
    ]
