# Generated by Django 6.0.1 on 2026-03-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Pronë', 'verbose_name_plural': 'Prona'},
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agent', verbose_name='Agjenti'),
        ),
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Kondicionim'),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='Ballkon'),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Ashensor'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kati'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'E Mobiluar'), ('unfurnished', 'Pa Mobilje'), ('partial', 'Pjesërisht')], max_length=20, verbose_name='Mobilimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False, verbose_name='Kopsht'),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.BooleanField(default=False, verbose_name='Ngrohje Qendrore'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_negotiable',
            field=models.BooleanField(default=False, verbose_name='Çmim i Negociueshëm'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mountain_view',
            field=models.BooleanField(default=False, verbose_name='Pamje Mali'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.BooleanField(default=False, verbose_name='Pishinë'),
        ),
        migrations.AddField(
            model_name='property',
            name='sea_view',
            field=models.BooleanField(default=False, verbose_name='Pamje Deti'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Disponueshme'), ('sold', 'Shitur'), ('rented', 'Dhënë me Qira'), ('reserved', 'Rezervuar')], default='available', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AddField(
            model_name='property',
            name='storage',
            field=models.BooleanField(default=False, verbose_name='Depo'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Katet Totale'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vizita'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Viti Ndërtimit'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='I Zgjedhur'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_m2',
            field=models.PositiveIntegerField(default=0, verbose_name='Sipërfaqe (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponueshme'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Banjo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dhoma Gjumi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Tiranë', max_length=100, verbose_name='Qyteti'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Përshkrimi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Foto Kryesore'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='I Ri'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Çmimi (€)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulli'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction',
            field=models.CharField(choices=[('sale', 'Shitje'), ('rent', 'Qira')], default='sale', max_length=10, verbose_name='Transaksioni'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Shtëpi'), ('land', 'Tokë'), ('commercial', 'Komerciale')], default='apartment', max_length=20, verbose_name='Lloji'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Titulli')),
                ('is_main', models.BooleanField(default=False, verbose_name='Foto Kryesore')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Rendi')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Foto Prone',
                'verbose_name_plural': 'Foto Pronash',
                'ordering': ['order', '-is_main'],
            },
        ),
    ]
