# Generated by Django 6.0.1 on 2026-03-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_options_property_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'I Ri'), ('read', 'Lexuar'), ('replied', 'Përgjigjur')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesazh Kontakti',
                'verbose_name_plural': 'Mesazhe Kontakti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Shtëpi'), ('land', 'Tokë'), ('commercial', 'Komerciale'), ('Villa', 'Vile')], default='apartment', max_length=20, verbose_name='Lloji'),
        ),
    ]
