# Generated by Django 6.0.1 on 2026-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_contactmessage_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'I Ri'), ('read', 'Lexuar'), ('replied', 'Përgjigjur'), ('spam', 'Spam')], default='new', max_length=20),
        ),
    ]
