# Generated by Django 6.0.1 on 2026-03-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_contactmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori Blogu',
                'verbose_name_plural': 'Kategori Blogu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulli')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imazhi kryesor')),
                ('body', models.TextField(verbose_name='Teksti')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Përshkrim i shkurtër')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Publikuar')], default='draft', max_length=20, verbose_name='Statusi')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='properties.agent', verbose_name='Autori')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='properties.postcategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Artikull',
                'verbose_name_plural': 'Artikuj',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('body', models.TextField(max_length=1000, verbose_name='Komenti')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovuar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.post')),
            ],
            options={
                'verbose_name': 'Koment',
                'verbose_name_plural': 'Komente',
                'ordering': ['created_at'],
            },
        ),
    ]
