# Generated by Django 6.0.1 on 2026-03-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_postcategory_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Emri')),
                ('last_name', models.CharField(max_length=100, verbose_name='Mbiemri')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoni')),
                ('position', models.CharField(choices=[('Office manager', 'Office Manager'), ('Office asistant', 'Office Assistant'), ('Real Estate consultant', 'Real Estate Consultant'), ('Graphic Designer', 'Graphic Designer'), ('Marketing Specialist', 'Marketing Specialist'), ('Social media specialist', 'Social Media Specialist')], max_length=50, verbose_name='Pozicioni')),
                ('cv', models.FileField(upload_to='karriera/cv/', verbose_name='CV')),
                ('status', models.CharField(choices=[('new', 'I Ri'), ('reviewing', 'Duke Shqyrtuar'), ('interview', 'Intervistë'), ('accepted', 'Pranuar'), ('rejected', 'Refuzuar')], default='new', max_length=20, verbose_name='Statusi')),
                ('notes', models.TextField(blank=True, verbose_name='Shënime (Admin)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplikim Karriere',
                'verbose_name_plural': 'Aplikimet e Karrierës',
                'ordering': ['-created_at'],
            },
        ),
    ]
