# Generated by Django 6.0.1 on 2026-03-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoni')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Data e Vizitës')),
                ('message', models.TextField(blank=True, verbose_name='Mesazhi')),
                ('status', models.CharField(choices=[('pending', 'Në Pritje'), ('confirmed', 'Konfirmuar'), ('rejected', 'Refuzuar'), ('completed', 'Kompletuar')], default='pending', max_length=20, verbose_name='Statusi')),
                ('reply', models.TextField(blank=True, verbose_name='Përgjigja e Agjentit')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Koha e Përgjigjes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Krijuar')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='properties.agent', verbose_name='Agjenti')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property', verbose_name='Prona')),
            ],
            options={
                'verbose_name': 'Kërkesë Vizite',
                'verbose_name_plural': 'Kërkesat e Vizitave',
                'ordering': ['-created_at'],
            },
        ),
    ]
