# Generated by Django 6.0.1 on 2026-03-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_visitrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aplikim karriere', 'verbose_name_plural': 'Aplikimet e karrierës'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Vitet e eksperiences'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='show_on_about',
            field=models.BooleanField(default=True, verbose_name='Shfaq në about'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.CharField(choices=[('buying', 'Blerje pronash'), ('selling', 'Shitje pronash'), ('rent_management', 'Menaxhim i pronave me qera'), ('property_valuation', 'Vlerësim prone')], default='residential', max_length=50, verbose_name='Specializimi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Mesazh i ri'), ('read', 'Lexuar'), ('replied', 'Përgjigjur'), ('spam', 'Spam')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Publiko')], default='draft', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dhoma gjumi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'E Mobiluar'), ('unfurnished', 'Pa mobilje'), ('partial', 'Pjesërish e mobiluar')], max_length=20, verbose_name='Mobilimi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=models.BooleanField(default=False, verbose_name='Ngrohje'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_negotiable',
            field=models.BooleanField(default=False, verbose_name='Çmim i negociueshëm'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mountain_view',
            field=models.BooleanField(default=False, verbose_name='Pamje mali'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sea_view',
            field=models.BooleanField(default=False, verbose_name='Pamje deti'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'E disponueshme'), ('sold', 'Shitur'), ('rented', 'Dhënë me qira'), ('reserved', 'Rezervuar')], default='available', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Katet totale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction',
            field=models.CharField(choices=[('sale', 'Shitje'), ('rent', 'Qira')], default='sale', max_length=10, verbose_name='Tipi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Shtëpi'), ('land', 'Tokë'), ('commercial', 'Komerciale'), ('Villa', 'Vile')], default='apartment', max_length=20, verbose_name='Lloji i prones'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Viti i ndërtimit'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Koha e përgjigjes'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='reply',
            field=models.TextField(blank=True, verbose_name='Përgjigja e agjentit'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Në pritje'), ('confirmed', 'Konfirmuar'), ('rejected', 'Refuzuar'), ('completed', 'Perfunduar')], default='pending', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data e vizitës'),
        ),
    ]
