# Generated by Django 6.0.1 on 2026-03-18 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='Emri i Klientit')),
                ('client_city', models.CharField(blank=True, max_length=80, verbose_name='Qyteti')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto Klienti')),
                ('agent_label', models.CharField(blank=True, help_text='P.sh. "Ilirjana Shordja" — përdoret vetëm nëse agjenti nuk është zgjedhur', max_length=120, verbose_name='Label Agjenti (nëse nuk ka FK)')),
                ('message', models.TextField(verbose_name='Mesazhi i Plotë')),
                ('message_short', models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para të mesazhit.', verbose_name='Preview (opsional)')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=5, verbose_name='Vlerësimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='I Zgjedhur (shfaq i pari)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Numër më i vogël = shfaqet i pari', verbose_name='Rendi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='properties.agent', verbose_name='Agjenti')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimoniale',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='property',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='VisitRequest',
        ),
    ]
