# Generated by Django 6.0.1 on 2026-03-18 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_testimonial_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-approved_at', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimoniale'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_photo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_active',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovuar'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Nuk shfaqet publikisht', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Nuk shfaqet publikisht', max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'Në pritje'), ('approved', 'Aprovuar'), ('rejected', 'Refuzuar')], default='pending', max_length=10, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='agent_label',
            field=models.CharField(blank=True, help_text='Plotësohet nga klienti nëse agjenti nuk është në listë', max_length=120, verbose_name='Emri Agjentit (manual)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=120, verbose_name='Emri'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dërguar'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='I Zgjedhur'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(verbose_name='Mesazhi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message_short',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', verbose_name='Preview (opsional)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rendi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='Vlerësimi'),
        ),
    ]
