# Generated by Django 6.0.1 on 2026-03-19 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Emri')),
                ('last_name', models.CharField(max_length=100, verbose_name='Mbiemri')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoni')),
                ('position', models.CharField(choices=[('Office manager', 'Office Manager'), ('Office asistant', 'Office Assistant'), ('Real Estate consultant', 'Real Estate Consultant'), ('Graphic Designer', 'Graphic Designer'), ('Marketing Specialist', 'Marketing Specialist'), ('Social media specialist', 'Social Media Specialist')], max_length=50, verbose_name='Pozicioni')),
                ('cv', models.FileField(upload_to='karriera/cv/', verbose_name='CV')),
                ('status', models.CharField(choices=[('new', 'I Ri'), ('reviewing', 'Duke Shqyrtuar'), ('interview', 'Intervistë'), ('accepted', 'Pranuar'), ('rejected', 'Refuzuar')], default='new', max_length=20, verbose_name='Statusi')),
                ('notes', models.TextField(blank=True, verbose_name='Shënime (Admin)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplikim karriere',
                'verbose_name_plural': 'Aplikimet e karrierës',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori Blogu',
                'verbose_name_plural': 'Kategori Blogu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulli')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imazhi kryesor')),
                ('body', models.TextField(verbose_name='Teksti')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Përshkrim i shkurtër')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Publiko')], default='draft', max_length=20, verbose_name='Statusi')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='properties.agent', verbose_name='Autori')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='properties.postcategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Artikull',
                'verbose_name_plural': 'Artikuj',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('body', models.TextField(max_length=1000, verbose_name='Komenti')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovuar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.post')),
            ],
            options={
                'verbose_name': 'Koment',
                'verbose_name_plural': 'Komente',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoni')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Data e vizitës')),
                ('message', models.TextField(blank=True, verbose_name='Mesazhi')),
                ('status', models.CharField(choices=[('pending', 'Në pritje'), ('confirmed', 'Konfirmuar'), ('rejected', 'Refuzuar'), ('completed', 'Perfunduar')], default='pending', max_length=20, verbose_name='Statusi')),
                ('reply', models.TextField(blank=True, verbose_name='Përgjigja e agjentit')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Koha e përgjigjes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Krijuar')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='properties.agent', verbose_name='Agjenti')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property', verbose_name='Prona')),
            ],
            options={
                'verbose_name': 'Kërkesë Vizite',
                'verbose_name_plural': 'Kërkesat e Vizitave',
                'ordering': ['-created_at'],
            },
        ),
    ]
