# Generated by Django 6.0.1 on 2026-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_jobapplication_postcategory_post_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(choices=[('vila', 'Vila Luksoze'), ('apartment', 'Apartament'), ('land', 'Tokë'), ('commercial', 'Dyqan/Komerciale')], max_length=20, verbose_name='Lloji')),
                ('rooms', models.CharField(blank=True, max_length=5, verbose_name='Dhoma')),
                ('area', models.CharField(max_length=20, verbose_name='Sipërfaqja (m²)')),
                ('period', models.CharField(blank=True, choices=[('para_1970', 'Para vitit 1970'), ('1971_1990', 'Midis 1971 dhe 1990'), ('1991_2010', 'Midis 1991 dhe 2010'), ('pas_2010', 'Pas vitit 2010')], max_length=20, verbose_name='Periudha')),
                ('condition', models.CharField(blank=True, choices=[('rinovim', 'Për të rinovuar'), ('mesatare', 'Gjendje mesatare'), ('mire', 'Gjendje e mirë'), ('perfekte', 'Në gjendje perfekte')], max_length=20, verbose_name='Gjendja')),
                ('parking', models.CharField(blank=True, choices=[('asnje', 'Asnjë'), ('garazh', 'Garazh'), ('parku', 'Parku i makinave')], max_length=20, verbose_name='Parkimi')),
                ('address', models.CharField(max_length=250, verbose_name='Adresa')),
                ('first_name', models.CharField(max_length=100, verbose_name='Emri')),
                ('last_name', models.CharField(max_length=100, verbose_name='Mbiemri')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('new', 'E re'), ('reviewing', 'Duke shqyrtuar'), ('sent', 'Vlerësim i dërguar'), ('closed', 'Mbyllur')], default='new', max_length=20, verbose_name='Statusi')),
                ('notes', models.TextField(blank=True, verbose_name='Shënime (Admin)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kërkesë Vlerësimi',
                'verbose_name_plural': 'Kërkesat e Vlerësimit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Shtëpi'), ('land', 'Tokë'), ('commercial', 'Komerciale'), ('Villa', 'Vile'), ('Garage', 'Garazh')], default='apartment', max_length=20, verbose_name='Lloji i prones'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rendi'),
        ),
    ]
