# Generated by Django 6.0.1 on 2026-03-24 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertyvaluation_alter_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.CharField(choices=[('buying', 'Blerje pronash'), ('selling', 'Shitje pronash'), ('rent management', 'Menaxhim i pronave me qera'), ('property valuation', 'Vlerësim prone')], default='residential', max_length=50, verbose_name='Specializimi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Mesazh i ri'), ('read', 'Lexuar'), ('replied', 'Pergjigjur'), ('spam', 'Spam')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Shenime (Admin)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True, verbose_name='E Disponueshme'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'E disponueshme'), ('sold', 'Shitur'), ('for rent', 'Për Qira'), ('rented', 'Dhënë me qira'), ('reserved', 'Rezervuar')], default='available', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='propertyvaluation',
            name='parking',
            field=models.CharField(blank=True, choices=[('Nuk ka parkim', 'Nuk ka parkim'), ('garazh', 'Garazh'), ('Parkim publik', 'Parkim publik')], max_length=20, verbose_name='Parkimi'),
        ),
        migrations.AlterField(
            model_name='propertyvaluation',
            name='status',
            field=models.CharField(choices=[('new', 'E re'), ('reviewing', 'Duke u shqyrtuar'), ('sent', 'Vlerësim i dërguar'), ('closed', 'Mbyllur')], default='new', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Derguar'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'Ne pritje'), ('approved', 'Aprovuar'), ('rejected', 'Refuzuar')], default='pending', max_length=10, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ne pritje'), ('confirmed', 'Konfirmuar'), ('rejected', 'Refuzuar'), ('completed', 'Perfunduar')], default='pending', max_length=20, verbose_name='Statusi'),
        ),
    ]
