# Generated by Django 6.0.1 on 2026-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_agent_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.CharField(choices=[('buying and selling', 'Shitje dhe blerje pronash'), ('rent management', 'Menaxhim i pronave me qera'), ('property valuation', 'Vlerësim prone')], default='residential', max_length=50, verbose_name='Specializimi'),
        ),
    ]
