# Generated by Django 6.0.1 on 2026-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_agent_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio_de',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bio_el',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bio_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bio_it',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bio_sq',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role_de',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, null=True, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role_el',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, null=True, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role_en',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, null=True, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role_fr',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, null=True, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role_it',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, null=True, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role_sq',
            field=models.CharField(default='Agjent Imobiliar', max_length=100, null=True, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_de',
            field=models.TextField(null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_el',
            field=models.TextField(null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_fr',
            field=models.TextField(null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_it',
            field=models.TextField(null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_sq',
            field=models.TextField(null=True, verbose_name='Teksti'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_de',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_el',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_fr',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_it',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_sq',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pershkrim i shkurter'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_el',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sq',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Përshkrimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_el',
            field=models.TextField(blank=True, null=True, verbose_name='Përshkrimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Përshkrimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Përshkrimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Përshkrimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_sq',
            field=models.TextField(blank=True, null=True, verbose_name='Përshkrimi'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_el',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_sq',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_el',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_it',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_sq',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagja/Zona'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_el',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_sq',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption_sq',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulli'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_de',
            field=models.TextField(null=True, verbose_name='Mesazhi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_el',
            field=models.TextField(null=True, verbose_name='Mesazhi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Mesazhi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_fr',
            field=models.TextField(null=True, verbose_name='Mesazhi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_it',
            field=models.TextField(null=True, verbose_name='Mesazhi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_short_de',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', null=True, verbose_name='Preview (opsional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_short_el',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', null=True, verbose_name='Preview (opsional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_short_en',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', null=True, verbose_name='Preview (opsional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_short_fr',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', null=True, verbose_name='Preview (opsional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_short_it',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', null=True, verbose_name='Preview (opsional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_short_sq',
            field=models.TextField(blank=True, help_text='Nëse lihet bosh, merren 220 karakteret e para', null=True, verbose_name='Preview (opsional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message_sq',
            field=models.TextField(null=True, verbose_name='Mesazhi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'E mobiluar'), ('unfurnished', 'Pa mobilje'), ('partial', 'Pjesërisht e mobiluar')], max_length=20, verbose_name='Mobilimi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'E disponueshme'), ('sold', 'Shitur'), ('for_rent', 'Për Qira'), ('rented', 'Dhënë me qira'), ('reserved', 'Rezervuar')], default='available', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Shtëpi'), ('land', 'Tokë'), ('commercial', 'Komerciale'), ('villa', 'Vilë'), ('garage', 'Garazh')], default='apartment', max_length=20, verbose_name='Lloji i prones'),
        ),
    ]
